// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/kavehjamshidi/arvan-challenge/domain"
	mock "github.com/stretchr/testify/mock"
)

// FileUploadQueue is an autogenerated mock type for the FileUploadQueue type
type FileUploadQueue struct {
	mock.Mock
}

// Store provides a mock function with given fields: file
func (_m *FileUploadQueue) Store(file domain.File) error {
	ret := _m.Called(file)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.File) error); ok {
		r0 = rf(file)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFileUploadQueue creates a new instance of FileUploadQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileUploadQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileUploadQueue {
	mock := &FileUploadQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
