// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// QuotaResetService is an autogenerated mock type for the QuotaResetService type
type QuotaResetService struct {
	mock.Mock
}

// ResetUserQuota provides a mock function with given fields: ctx
func (_m *QuotaResetService) ResetUserQuota(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewQuotaResetService creates a new instance of QuotaResetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuotaResetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuotaResetService {
	mock := &QuotaResetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
